[build-system]
# setuptools>=61 for PEP 621 support
requires = ["setuptools>=61.0", "wheel", "Cython>=3.0", "numpy>=2.0"]
build-backend = "setuptools.build_meta"

[project]
name = "scikit-sparse"
version = "0.5.0"
description = "Scikit-sparse is a Python wrapper for the SuiteSparse sparse matrix library."
readme = "README.md"
requires-python = ">=3.10"
license = "BSD-2-Clause"
license-files = ["LICENSE.txt"]

authors = [
    { name = "David Cournapeau", email = "cournape@gmail.com" },
    { name = "Nathaniel Smith", email = "njs@pobox.com" },
    { name = "Dag Sverre Seljebotn", email = "dagss@student.matnat.uio.no" },
    { name = "Leon Barrett", email = "lbarrett@climate.com" },
    { name = "Yuri", email = "yuri@tsoft.com" },
    { name = "Antony Lee", email = "anntzer.lee@gmail.com" },
    { name = "Alex Grigorievskiy", email = "alex.grigorievskiy@gmail.com" },
    { name = "Joscha Reimer", email = "jor@informatik.uni-kiel.de" },
    { name = "Justin Ellis", email = "justin.ellis18@gmail.com" },
    { name = "Aaron Johnson", email = "aaron9035@gmail.com" },
    { name = "Bernard Roesler", email = "bernard.roesler@gmail.com" },
]
maintainers = [
    { name = "Bernard Roesler", email = "bernard.roesler@gmail.com" },
]

keywords = ["sparse", "matrix", "linear algebra", "scipy", "numpy"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Programming Language :: Cython",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

dependencies = [
    "numpy>2.0",
    "scipy>=1.14",
]

[project.optional-dependencies]
dev = [
    "build",
    "pre-commit",
    "pytest",
    "ruff",
    "sphinx",
]

[project.urls]
"Homepage" = "https://github.com/scikit-sparse/scikit-sparse"
"Bug Tracker" = "https://github.com/scikit-sparse/scikit-sparse/issues"

# This data is excluded from the wheel package, but not necessarily from the
# sdist (for sdist, see: MANIFEST.in)
[tool.setuptools.exclude-package-data]
sksparse = ["*.c", "*.pyx"]

# [tool.setuptools.packages.find]
# exclude = ["cython_debug"]

[tool.cython]
language_level = "3"
# gdb_debug = true

[tool.ruff]
line-length = 88
target-version = "py310"
extend-exclude = [
    "doc",
]

[tool.ruff.lint]
extend-select = [
    'B',    # flake8-bugbear
    'C4',   # flake8-comprehensions
    'D',    # docstring errors
    'E',    # pycodestyle errors
    'F',    # pyflakes errors
    'I',    # isort errors (import sorting)
    'ISC',  # flake8-implicit-str-concat
    'NPY',  # numpy-specific checks
    'PD',   # pandas-vet
    'PIE',  # flake8-pie
    'PL',   # pylint errors
    'PTH',  # use Path vs os
    'UP',   # pyupgrade
    'W',    # pycodestyle warnings (whitespace)
]

ignore = [
    'B028',     # No explicit `stacklevel` keyword argument found
    'B904',     # Within an `except` clause distinguish raised exceptions from errors in exception handling
    'B905',     # `zip()` without an explicit `strict=` parameter
    'D104',     # Missing docstring in __init__
    'D105',     # Missing docstring in magic method
    'D205',     # 1 blank line required between summary line and description
    'E741',     # ambiguous variable name (l, O, I)
    'PIE790',   # Unnecessary `pass` statement
    'PLC2401',  # non-ASCII characters
    'PLR0912',  # too many branches (max-branches)
    'PLR0913',  # too many arguments (max-args)
    'PLR0915',  # too many statements (max-statements)
    'PLR2004',  # magic value used in comparison
]

[tool.ruff.lint.isort]
known-first-party = ["sksparse"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ['I001', 'F403', 'F405']  # ignore import sorting, wildcard imports, and undefined names
"test_*.py" = ['D101', 'D102', 'D103', 'E501']  # ignore docstring checks in test files
"setup.py" = ['D100', 'D101', 'D102', 'D103', 'D104']  # ignore docstrings

[tool.ruff.lint.pydocstyle]
convention = "numpy"
