[build-system]
# setuptools>=61 for PEP 621 support
requires = ["setuptools>=61.0", "wheel", "Cython>=3.0", "numpy>=2.0"]
build-backend = "setuptools.build_meta"

[project]
name = "scikit-sparse"
version = "0.5.0"
description = "Scikit sparse matrix package"
readme = "README.md"
requires-python = ">=3.10"
license = "BSD-2-Clause"
license-files = ["LICENSE.txt"]

authors = [
    { name = "David Cournapeau", email = "cournape@gmail.com" },
    { name = "Nathaniel Smith", email = "njs@pobox.com" },
    { name = "Dag Sverre Seljebotn", email = "dagss@student.matnat.uio.no" },
    { name = "Leon Barrett", email = "lbarrett@climate.com" },
    { name = "Yuri", email = "yuri@tsoft.com" },
    { name = "Antony Lee", email = "anntzer.lee@gmail.com" },
    { name = "Alex Grigorievskiy", email = "alex.grigorievskiy@gmail.com" },
    { name = "Joscha Reimer", email = "jor@informatik.uni-kiel.de" },
    { name = "Justin Ellis", email = "justin.ellis18@gmail.com" },
    { name = "Aaron Johnson", email = "aaron9035@gmail.com" },
    { name = "Bernard Roesler", email = "bernard.roesler@gmail.com" },
]
maintainers = [
    { name = "Aaron Johnson", email = "aaron9035@gmail.com" }
]

keywords = ["sparse", "matrix", "linear algebra", "scipy", "numpy"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Programming Language :: Cython",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

dependencies = [
    "numpy>2.0",
    "scipy>=1.14",
]

[project.urls]
"Homepage" = "https://github.com/scikit-sparse/scikit-sparse"
"Bug Tracker" = "https://github.com/scikit-sparse/scikit-sparse/issues"

[tool.black]
line-length = 88
target_version = ['py311']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | _build
    | buck-out
    | build
    | dist
    | doc
    | venv
  )/
)
'''
