name: CI targets

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release: 
    types:
      - published


jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      env:
        PIP_DISABLE_PIP_VERSION_CHECK: 1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install non-python dependencies on mac
      if: runner.os == 'macOS'
      run: |
        brew install suite-sparse
    - name: Install non-python dependencies on linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install libsuitesparse-dev
    - name: Install dependencies and package
      run: |
        pip install --upgrade pip
        pip install -e .[dev]
    - name: Display installed packages
      run: |
        python -m pip list
    # TODO: update existing code to pass linting checks
    # - name: Run lint
    #   run:  ruff check
    - name: Test with pytest
      run: pytest -v tests

  build:
    needs: [tests]
    name: Build source distribution
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install non-python dependencies on linux
      run: |
        sudo apt-get install libsuitesparse-dev
    - name: Build wheel and sdist
      run: |
        pip install --upgrade pip
        pip install build
        python -m build
    - name: Test the sdist
      run: |
        python -m venv venv-sdist
        source venv-sdist/bin/activate
        python -m pip install --upgrade pip
        SDIST_FILE=$(find dist -name 'scikit_sparse*.tar.gz')
        python -m pip install "${SDIST_FILE}[dev]"
        python -c "import sksparse; print(sksparse.__version__)"
        python -m pytest -v tests
    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/*

  deploy:
    needs: [tests, build]
    runs-on: ubuntu-latest
    environment: deploy
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    if: github.event_name == 'release'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Download wheel/dist from build
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist
    - name: Build and publish
      uses: pypa/gh-action-pypi-publish@release/v1
