name: Deploy

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build:
    uses: ./.github/workflows/build-check.yml

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    environment: deploy
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - name: Download sdist from Ubuntu 3.10
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Remove wheel files (publish sdist only)
        run: |
          rm -f dist/*.whl
          ls -lh dist/

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
